### PR TITLE
Clarify what value is used for `ServerName`.

### PR DESCRIPTION
**Pull request by studersi**
I think this description should still be within reach of most readers.

### CODE REVIEW

**Comment by studersi** [comment]
Actually `fully qualified host name` is still better than `fully qualified domain name` (see second commit)..

**Comment by dune73** [comment]
You now mix _domain name_ and _host name_.

**Comment by studersi** [comment]
You're right, I only change one of the occurrences back to 'host name'.

**Comment by dune73** [comment]
Hmm. This does not work.

It was technically wrong before your change. Now it is correct but hard to understand.

Alternatively, we could leave the 2nd sentence away completely. In the end, `ServerName` is self-explanatory and our explications are only puzzling people.

**Comment by studersi** [comment]
Removed the second sentence.

**Comment by dune73** [comment]
Good. Let's stick to this. Thanks for PR.

**Pull request merged**
