### PR TITLE
Improve wording.

### PR DESCRIPTION
**Pull request by studersi**

### CODE REVIEW

**Comment by dune73** [comment]
There is an additional <space> on the 2nd line. Please remove.

**Comment by studersi** [comment]
I'm not sure what you mean by that. There is an additional what on which second line?

**Comment by dune73** [comment]
I wrote `<space>` and github did not show it. 

It's `and  that`.

**Comment by studersi** [comment]
I see. Fixed now.

**Comment by dune73** [comment]
Thank you for fixing. And the PR.

**Pull request merged**
